# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mockup_test.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(375, 812)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setStyleSheet("QWidget {\n"
"background-color: #161A20;\n"
"}")
        MainWindow.setProperty("operands", "")
        self.Operands = QtWidgets.QWidget(MainWindow)
        self.Operands.setObjectName("Operands")
        self.division = QtWidgets.QPushButton(self.Operands)
        self.division.setGeometry(QtCore.QRect(277, 351, 83, 79))
        self.division.setStyleSheet("QPushButton {\n"
"    background-color: #0060E5;\n"
"    color: #CBE1FF;\n"
"    border-radius: 2px;\n"
"    border-top-right-radius: 8px;\n"
"    font-family: roboto;\n"
"    font-size: 38px;\n"
"   }\n"
"\n"
"")
        self.division.setProperty("operands", "")
        self.division.setObjectName("division")
        self.equal = QtWidgets.QPushButton(self.Operands)
        self.equal.setGeometry(QtCore.QRect(277, 683, 83, 79))
        self.equal.setStyleSheet("QPushButton {\n"
"    background-color: #0060E5;\n"
"    color: #CBE1FF;\n"
"    border-radius: 2px;\n"
"    border-bottom-right-radius: 8px;\n"
"    font-family: roboto;\n"
"font-size: 28px;\n"
"   }\n"
"\n"
"")
        self.equal.setObjectName("equal")
        self.multiplication = QtWidgets.QPushButton(self.Operands)
        self.multiplication.setGeometry(QtCore.QRect(277, 434, 83, 79))
        self.multiplication.setStyleSheet("QPushButton {\n"
"    background-color: #0060E5;\n"
"    color: #CBE1FF;\n"
"    border-radius: 2px;\n"
"    font-family: roboto;\n"
"    font-size: 28px;\n"
"   }\n"
"\n"
"")
        self.multiplication.setObjectName("multiplication")
        self.minus = QtWidgets.QPushButton(self.Operands)
        self.minus.setGeometry(QtCore.QRect(277, 517, 83, 79))
        self.minus.setStyleSheet("QPushButton {\n"
"    background-color: #0060E5;\n"
"    color: #CBE1FF;\n"
"    border-radius: 2px;\n"
"    font-family: roboto;\n"
"font-size: 28px;\n"
"   }\n"
"\n"
"")
        self.minus.setObjectName("minus")
        self.plus = QtWidgets.QPushButton(self.Operands)
        self.plus.setGeometry(QtCore.QRect(277, 600, 83, 79))
        self.plus.setStyleSheet("QPushButton {\n"
"    background-color: #0060E5;\n"
"    color: #CBE1FF;\n"
"    border-radius: 2px;\n"
"    font-family: roboto;\n"
"font-size: 28px;\n"
"   }\n"
"\n"
"")
        self.plus.setObjectName("plus")
        self.AC = QtWidgets.QPushButton(self.Operands)
        self.AC.setGeometry(QtCore.QRect(16, 351, 83, 79))
        self.AC.setStyleSheet("QPushButton {\n"
"    background-color: #363E4D;\n"
"    color: #CBE1FF;\n"
"    border-radius: 2px;\n"
"    border-top-left-radius: 8px;\n"
"    font-family: roboto;\n"
"    font-size: 28px;\n"
"   }\n"
"\n"
"")
        self.AC.setProperty("operands", "")
        self.AC.setObjectName("AC")
        self.paranth = QtWidgets.QPushButton(self.Operands)
        self.paranth.setGeometry(QtCore.QRect(103, 351, 83, 79))
        self.paranth.setStyleSheet("QPushButton {\n"
"    background-color: #363E4D;\n"
"    color: #CBE1FF;\n"
"    border-radius: 2px;\n"
"    font-family: roboto;\n"
"    font-size: 28px;\n"
"   }\n"
"\n"
"")
        self.paranth.setProperty("operands", "")
        self.paranth.setObjectName("paranth")
        self.percent = QtWidgets.QPushButton(self.Operands)
        self.percent.setGeometry(QtCore.QRect(190, 351, 83, 79))
        self.percent.setStyleSheet("QPushButton {\n"
"    background-color: #363E4D;\n"
"    color: #CBE1FF;\n"
"    border-radius: 2px;\n"
"    font-family: roboto;\n"
"    font-size: 28px;\n"
"   }\n"
"\n"
"")
        self.percent.setProperty("operands", "")
        self.percent.setObjectName("percent")
        self.nine = QtWidgets.QPushButton(self.Operands)
        self.nine.setGeometry(QtCore.QRect(190, 434, 83, 79))
        self.nine.setStyleSheet("QPushButton {\n"
"    background-color: #242933;\n"
"    color: #CBE1FF;\n"
"    border-radius: 2px;\n"
"    font-family: roboto;\n"
"    font-size: 28px;\n"
"   }\n"
"\n"
"")
        self.nine.setProperty("operands", "")
        self.nine.setObjectName("nine")
        self.seven = QtWidgets.QPushButton(self.Operands)
        self.seven.setGeometry(QtCore.QRect(16, 434, 83, 79))
        self.seven.setStyleSheet("QPushButton {\n"
"    background-color: #242933;\n"
"    color: #CBE1FF;\n"
"    border-radius: 2px;\n"
"    font-family: roboto;\n"
"    font-size: 28px;\n"
"   }\n"
"\n"
"")
        self.seven.setProperty("operands", "")
        self.seven.setObjectName("seven")
        self.eight = QtWidgets.QPushButton(self.Operands)
        self.eight.setGeometry(QtCore.QRect(103, 434, 83, 79))
        self.eight.setStyleSheet("QPushButton {\n"
"    background-color: #242933;\n"
"    color: #CBE1FF;\n"
"    border-radius: 2px;\n"
"    font-family: roboto;\n"
"    font-size: 28px;\n"
"   }\n"
"\n"
"")
        self.eight.setProperty("operands", "")
        self.eight.setObjectName("eight")
        self.four = QtWidgets.QPushButton(self.Operands)
        self.four.setGeometry(QtCore.QRect(16, 517, 83, 79))
        self.four.setStyleSheet("QPushButton {\n"
"    background-color: #242933;\n"
"    color: #CBE1FF;\n"
"    border-radius: 2px;\n"
"    font-family: roboto;\n"
"    font-size: 28px;\n"
"   }\n"
"\n"
"")
        self.four.setProperty("operands", "")
        self.four.setObjectName("four")
        self.five = QtWidgets.QPushButton(self.Operands)
        self.five.setGeometry(QtCore.QRect(103, 517, 83, 79))
        self.five.setStyleSheet("QPushButton {\n"
"    background-color: #242933;\n"
"    color: #CBE1FF;\n"
"    border-radius: 2px;\n"
"    font-family: roboto;\n"
"    font-size: 28px;\n"
"   }\n"
"\n"
"")
        self.five.setProperty("operands", "")
        self.five.setObjectName("five")
        self.six = QtWidgets.QPushButton(self.Operands)
        self.six.setGeometry(QtCore.QRect(190, 517, 83, 79))
        self.six.setStyleSheet("QPushButton {\n"
"    background-color: #242933;\n"
"    color: #CBE1FF;\n"
"    border-radius: 2px;\n"
"    font-family: roboto;\n"
"    font-size: 28px;\n"
"   }\n"
"\n"
"")
        self.six.setProperty("operands", "")
        self.six.setObjectName("six")
        self.one = QtWidgets.QPushButton(self.Operands)
        self.one.setGeometry(QtCore.QRect(16, 600, 83, 79))
        self.one.setStyleSheet("QPushButton {\n"
"    background-color: #242933;\n"
"    color: #CBE1FF;\n"
"    border-radius: 2px;\n"
"    font-family: roboto;\n"
"    font-size: 28px;\n"
"   }\n"
"\n"
"")
        self.one.setProperty("operands", "")
        self.one.setObjectName("one")
        self.two = QtWidgets.QPushButton(self.Operands)
        self.two.setGeometry(QtCore.QRect(103, 600, 83, 79))
        self.two.setStyleSheet("QPushButton {\n"
"    background-color: #242933;\n"
"    color: #CBE1FF;\n"
"    border-radius: 2px;\n"
"    font-family: roboto;\n"
"    font-size: 28px;\n"
"   }\n"
"\n"
"")
        self.two.setProperty("operands", "")
        self.two.setObjectName("two")
        self.three = QtWidgets.QPushButton(self.Operands)
        self.three.setGeometry(QtCore.QRect(190, 600, 83, 79))
        self.three.setStyleSheet("QPushButton {\n"
"    background-color: #242933;\n"
"    color: #CBE1FF;\n"
"    border-radius: 2px;\n"
"    font-family: roboto;\n"
"    font-size: 28px;\n"
"   }\n"
"\n"
"")
        self.three.setProperty("operands", "")
        self.three.setObjectName("three")
        self.dot = QtWidgets.QPushButton(self.Operands)
        self.dot.setGeometry(QtCore.QRect(190, 683, 83, 79))
        self.dot.setStyleSheet("QPushButton {\n"
"    background-color: #242933;\n"
"    color: #CBE1FF;\n"
"    border-radius: 2px;\n"
"    font-family: roboto;\n"
"    font-size: 28px;\n"
"   }\n"
"\n"
"")
        self.dot.setProperty("operands", "")
        self.dot.setObjectName("dot")
        self.zero = QtWidgets.QPushButton(self.Operands)
        self.zero.setGeometry(QtCore.QRect(103, 683, 83, 79))
        self.zero.setStyleSheet("QPushButton {\n"
"    background-color: #242933;\n"
"    color: #CBE1FF;\n"
"    border-radius: 2px;\n"
"    font-family: roboto;\n"
"    font-size: 28px;\n"
"   }\n"
"\n"
"")
        self.zero.setProperty("operands", "")
        self.zero.setObjectName("zero")
        self.plusNminus = QtWidgets.QPushButton(self.Operands)
        self.plusNminus.setGeometry(QtCore.QRect(16, 683, 83, 79))
        self.plusNminus.setStyleSheet("QPushButton {\n"
"    background-color: #363E4D;\n"
"    color: #CBE1FF;\n"
"    border-radius: 2px;\n"
"    border-bottom-left-radius: 8px;\n"
"    font-family: roboto;\n"
"    font-size: 28px;\n"
"   }\n"
"\n"
"")
        self.plusNminus.setProperty("operands", "")
        self.plusNminus.setObjectName("plusNminus")
        self.pushButton = QtWidgets.QPushButton(self.Operands)
        self.pushButton.setGeometry(QtCore.QRect(24, 316, 66, 23))
        self.pushButton.setStyleSheet("QPushButton {\n"
"    background-color: #D9D9D9;\n"
"    color: #212D2A;\n"
"    border-radius: 11px;\n"
"    font-family: roboto;\n"
"    font-size: 17px;\n"
"   }\n"
"\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.Adv = QtWidgets.QPushButton(self.Operands)
        self.Adv.setGeometry(QtCore.QRect(111, 316, 66, 23))
        self.Adv.setStyleSheet("QPushButton {\n"
"    background-color: #D9D9D9;\n"
"    color: #212D2A;\n"
"    border-radius: 11px;\n"
"    font-family: roboto;\n"
"    font-size: 17px;\n"
"   }\n"
"\n"
"")
        self.Adv.setObjectName("Adv")
        self.clock = QtWidgets.QPushButton(self.Operands)
        self.clock.setGeometry(QtCore.QRect(252, 129, 95, 25))
        self.clock.setStyleSheet("QPushButton {\n"
"    background-color: #363E4C;\n"
"    color: #CBE1FF;\n"
"    font-weight: lighter;\n"
"    border-radius: 11px;\n"
"    font-family: roboto;\n"
"    font-size: 17px;\n"
"   }\n"
"\n"
"")
        icon = QtGui.QIcon.fromTheme("clock")
        self.clock.setIcon(icon)
        self.clock.setObjectName("clock")
        self.Calc = QtWidgets.QPushButton(self.Operands)
        self.Calc.setGeometry(QtCore.QRect(16, 60, 114, 40))
        self.Calc.setStyleSheet("QPushButton {\n"
"    background-color: #0060E5;\n"
"    color: #FFFFFF;\n"
"    font-family: roboto;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    border-top-left-radius: 4px;\n"
"    border-bottom-left-radius:4px;\n"
"   }\n"
"\n"
"")
        self.Calc.setProperty("operands", "")
        self.Calc.setObjectName("Calc")
        self.Graph = QtWidgets.QPushButton(self.Operands)
        self.Graph.setGeometry(QtCore.QRect(130, 60, 114, 40))
        self.Graph.setStyleSheet("QPushButton {\n"
"    background-color: #2D3440;\n"
"    color: #FFFFFF;\n"
"    font-family: roboto;\n"
"    font-size: 14px;\n"
"   }\n"
"\n"
"")
        self.Graph.setProperty("operands", "")
        self.Graph.setObjectName("Graph")
        self.Menu = QtWidgets.QPushButton(self.Operands)
        self.Menu.setGeometry(QtCore.QRect(240, 60, 114, 40))
        self.Menu.setStyleSheet("QPushButton {\n"
"    background-color: #2D3440;\n"
"    color: #FFFFFF;\n"
"    font-family: roboto;\n"
"    font-size: 14px;\n"
"    border-top-right-radius: 4px;\n"
"    border-bottom-right-radius:4px;\n"
"   }\n"
"\n"
"")
        self.Menu.setProperty("operands", "")
        self.Menu.setObjectName("Menu")
        self.inputs = QtWidgets.QTextEdit(self.Operands)
        self.inputs.setGeometry(QtCore.QRect(16, 165, 346, 80))
        self.inputs.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.inputs.setStyleSheet("QTextEdit {\n"
"background-color: #161A20;\n"
"color: #FFFFFF;\n"
"}")
        self.inputs.setObjectName("inputs")
        self.output = QtWidgets.QLineEdit(self.Operands)
        self.output.setGeometry(QtCore.QRect(0, 260, 375, 48))
        self.output.setStyleSheet("QLineEdit {\n"
"background-color: #20252E;\n"
"color: #FFFFFF;\n"
"font-size: 24px;\n"
"font-weight: lighter;\n"
"}")
        self.output.setObjectName("output")
        self.inputs.raise_()
        self.division.raise_()
        self.equal.raise_()
        self.multiplication.raise_()
        self.minus.raise_()
        self.plus.raise_()
        self.AC.raise_()
        self.paranth.raise_()
        self.percent.raise_()
        self.nine.raise_()
        self.seven.raise_()
        self.eight.raise_()
        self.four.raise_()
        self.five.raise_()
        self.six.raise_()
        self.one.raise_()
        self.two.raise_()
        self.three.raise_()
        self.dot.raise_()
        self.zero.raise_()
        self.plusNminus.raise_()
        self.pushButton.raise_()
        self.Adv.raise_()
        self.clock.raise_()
        self.Calc.raise_()
        self.Graph.raise_()
        self.Menu.raise_()
        self.output.raise_()
        MainWindow.setCentralWidget(self.Operands)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 375, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.division.setText(_translate("MainWindow", "÷"))
        self.equal.setText(_translate("MainWindow", "="))
        self.multiplication.setText(_translate("MainWindow", "x"))
        self.minus.setText(_translate("MainWindow", "–"))
        self.plus.setText(_translate("MainWindow", "+"))
        self.AC.setText(_translate("MainWindow", "AC"))
        self.paranth.setText(_translate("MainWindow", "( )"))
        self.percent.setText(_translate("MainWindow", "%"))
        self.nine.setText(_translate("MainWindow", "9"))
        self.seven.setText(_translate("MainWindow", "7"))
        self.eight.setText(_translate("MainWindow", "8"))
        self.four.setText(_translate("MainWindow", "4"))
        self.five.setText(_translate("MainWindow", "5"))
        self.six.setText(_translate("MainWindow", "6"))
        self.one.setText(_translate("MainWindow", "1"))
        self.two.setText(_translate("MainWindow", "2"))
        self.three.setText(_translate("MainWindow", "3"))
        self.dot.setText(_translate("MainWindow", "."))
        self.zero.setText(_translate("MainWindow", "0"))
        self.plusNminus.setText(_translate("MainWindow", "+/–"))
        self.pushButton.setText(_translate("MainWindow", "Trig"))
        self.Adv.setText(_translate("MainWindow", "Adv"))
        self.clock.setText(_translate("MainWindow", "clock"))
        self.Calc.setText(_translate("MainWindow", "Calculator"))
        self.Graph.setText(_translate("MainWindow", "Graph"))
        self.Menu.setText(_translate("MainWindow", "Menu"))
        self.inputs.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">5(254)/3</p></body></html>"))
        self.output.setText(_translate("MainWindow", "19,134"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
