# Form implementation generated from reading ui file 'unit_main.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

from gui.components.textarea import MvgCalcExpressionTextField
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_unit_converter(object):
    def setupUi(self, unit_converter):
        unit_converter.setObjectName("unit_converter")
        unit_converter.resize(318, 102)
        self.gridLayout = QtWidgets.QGridLayout(unit_converter)
        self.gridLayout.setObjectName("gridLayout")
        self.unit_2 = MvgCalcExpressionTextField(parent=unit_converter)
        self.unit_2.setObjectName("unit_2")
        self.gridLayout.addWidget(self.unit_2, 3, 1, 1, 1)
        self.label = QtWidgets.QLabel(parent=unit_converter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        self.unit_listbox_2 = QtWidgets.QPushButton(parent=unit_converter)
        self.unit_listbox_2.setObjectName("unit_listbox_2")
        self.gridLayout.addWidget(self.unit_listbox_2, 3, 2, 1, 1)
        self.unit_listbox_1 = QtWidgets.QPushButton(parent=unit_converter)
        self.unit_listbox_1.setObjectName("unit_listbox_1")
        self.gridLayout.addWidget(self.unit_listbox_1, 2, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=unit_converter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 1)
        self.unit_1 = MvgCalcExpressionTextField(parent=unit_converter)
        self.unit_1.setObjectName("unit_1")
        self.gridLayout.addWidget(self.unit_1, 2, 1, 1, 1)
        self.measures_listbox = QtWidgets.QPushButton(parent=unit_converter)
        self.measures_listbox.setObjectName("measures_listbox")
        self.gridLayout.addWidget(self.measures_listbox, 0, 0, 1, 1)

        self.retranslateUi(unit_converter)
        QtCore.QMetaObject.connectSlotsByName(unit_converter)

    def retranslateUi(self, unit_converter):
        _translate = QtCore.QCoreApplication.translate
        unit_converter.setWindowTitle(_translate("unit_converter", "Form"))
        self.label.setText(_translate("unit_converter", "From:"))
        self.unit_listbox_2.setText(_translate("unit_converter", "Units"))
        self.unit_listbox_1.setText(_translate("unit_converter", "Units"))
        self.label_2.setText(_translate("unit_converter", "To:"))
        self.measures_listbox.setText(_translate("unit_converter", "Length"))
